export const Cars = [
  {
    brand: "Renault",
    model: "Megane",
    year: 2017,
    fuel_type: "Diesel",
    horse_power: 110,
    gearbox: "Automatic",
    combustion: 5,
    price_category: "Basic",
    available: true,
    price: 120,
    image:
      "https://renaultpasikowski.pl/wp-content/uploads/2021/11/xMEGANE-PASIKOWSKI.png.pagespeed.ic.2x8E1Xh0eC.png",
  },
  {
    brand: "Seat",
    model: "Leon IV",
    year: 2022,
    fuel_type: "Gasoline",
    horse_power: 130,
    gearbox: "Manual",
    combustion: 6,
    price_category: "Standard",
    available: true,
    price: 150,
    image: "https://kalkulator.vwbank.pl/images/calculator/leon.png",
  },
  {
    brand: "Audi",
    model: "A4 B9",
    year: 2019,
    fuel_type: "Gasoline",
    horse_power: 252,
    gearbox: "Automatic",
    combustion: 8,
    price_category: "Medium",
    available: true,
    price: 250,
    image:
      "https://mediaservice.audi.com/media/live/50900/fly720x405n1/8wc/2020.png",
  },
  {
    brand: "BMW",
    model: "M5",
    year: 2021,
    fuel_type: "Gasoline",
    horse_power: 600,
    gearbox: "Automatic",
    combustion: 12,
    price_category: "Premium",
    available: true,
    price: 400,
    image:
      "https://atuk-prod-cz-dealer-sites-resources.s3-eu-west-1.amazonaws.com/imglib/BMWDealer2016/img/newcars/intropics/M5-Saloon-intro.png",
  },
  {
    brand: "Audi",
    model: "A3",
    year: 2023,
    fuel_type: "Gasoline",
    horse_power: 110,
    gearbox: "Automatic",
    combustion: 6,
    price_category: "Medium",
    available: true,
    price: 200,
    image:
      "https://mediaservice.audi.com/media/live/50900/fly1400x601n1/8yaar/2021.png?wid=850",
  },
  {
    brand: "Tuk",
    model: "Tuk",
    year: 1989,
    fuel_type: "Gasoline",
    horse_power: 20,
    gearbox: "Manual",
    combustion: 4,
    price_category: "Basic",
    available: true,
    price: 100,
    image:
      "https://cdn.pixabay.com/photo/2019/03/10/16/05/tuk-tuk-4046465_960_720.png",
  },
  {
    brand: "FSO",
    model: "Polonez",
    year: 1999,
    fuel_type: "Gasoline",
    horse_power: 82,
    gearbox: "Manual",
    combustion: 7,
    price_category: "Standard",
    available: true,
    price: 120,
    image:
      "https://panekcs.pl/templates/yootheme/cache/78/polonez_340x165-7885d540.png",
  },
  {
    brand: "URSUS",
    model: "C-360",
    year: 1980,
    fuel_type: "Diesel",
    horse_power: 60,
    gearbox: "Manual",
    combustion: 7,
    price_category: "Premium",
    available: true,
    price: 80,
    image: "https://www.e-skladnica.pl/public/assets/ursus2c360.jpg.png",
  },
  // {
  //   brand: "",
  //   model: "",
  //   year: 2020,
  //   fuel_type: "",
  //   horse_power: 1,
  //   gearbox: "",
  //   combustion: 1,
  //   price_category: "Basic",
  //   available: true,
  //  price: 0,
  //  image: ""
  // },
];
