export const Cars = [
  {
    brand: "Renault",
    model: "Megane",
    year: 2017,
    fuel_type: "Diesel",
    horse_power: 110,
    gearbox: "Automatic",
    combustion: 5,
    price_category: "Basic",
    available: true,
    price: 120,
    image:
      "https://renaultpasikowski.pl/wp-content/uploads/2021/11/xMEGANE-PASIKOWSKI.png.pagespeed.ic.2x8E1Xh0eC.png",
  },
  {
    brand: "Seat",
    model: "Leon IV",
    year: 2022,
    fuel_type: "Gasoline",
    horse_power: 130,
    gearbox: "Manual",
    combustion: 6,
    price_category: "Standard",
    available: true,
    price: 150,
    image: "https://kalkulator.vwbank.pl/images/calculator/leon.png",
  },
  {
    brand: "Audi",
    model: "A4 B9",
    year: 2019,
    fuel_type: "Gasoline",
    horse_power: 252,
    gearbox: "Automatic",
    combustion: 8,
    price_category: "Medium",
    available: true,
    price: 250,
    image:
      "https://mediaservice.audi.com/media/live/50900/fly720x405n1/8wc/2020.png",
  },
  {
    brand: "BMW",
    model: "M5",
    year: 2021,
    fuel_type: "Gasoline",
    horse_power: 600,
    gearbox: "Automatic",
    combustion: 12,
    price_category: "Premium",
    available: true,
    price: 400,
    image:
      "https://atuk-prod-cz-dealer-sites-resources.s3-eu-west-1.amazonaws.com/imglib/BMWDealer2016/img/newcars/intropics/M5-Saloon-intro.png",
  },
  // {
  //   brand: "",
  //   model: "",
  //   year: 2020,
  //   fuel_type: "",
  //   horse_power: 1,
  //   gearbox: "",
  //   combustion: 1,
  //   price_category: "Basic",
  //   available: true,
  // },
];
