export const Cars = [
  {
    brand: "Renault",
    model: "Megane",
    year: 2017,
    fuel_type: "Diesel",
    horse_power: 110,
    gearbox: "Automatic",
    combustion: 5,
    price_category: "Basic",
    available: true,
    image:
      "https://www.renault.pl/agg/vn/unique/ONE_DACIA_PP_LARGE_DENSITY1/r_brandSite_carPicker_1.png?uri=https%3A%2F%2Fpl.co.rplug.renault.com%2Fproduct%2Fmodel%2FMB4%2Fmegane%2Fc%2FA-ENS_0MDL2PSL1NIVEQPT8_-TEKPN",
  },
  {
    brand: "Seat",
    model: "Leon IV",
    year: 2022,
    fuel_type: "Gasoline",
    horse_power: 130,
    gearbox: "Manual",
    combustion: 6,
    price_category: "Standard",
    available: true,
    image: "https://kalkulator.vwbank.pl/images/calculator/leon.png",
  },
  {
    brand: "Audi",
    model: "A4 B9",
    year: 2019,
    fuel_type: "Gasoline",
    horse_power: 252,
    gearbox: "Automatic",
    combustion: 8,
    price_category: "Medium",
    available: true,
    image:
      "https://mediaservice.audi.com/media/live/50900/fly720x405n1/8wc/2020.png",
  },
  {
    brand: "BMW",
    model: "M5",
    year: 2021,
    fuel_type: "Gasoline",
    horse_power: 600,
    gearbox: "Automatic",
    combustion: 12,
    price_category: "Premium",
    available: true,
    image:
      "https://www.bmw.pl/content/dam/bmw/common/all-models/m-series/m5-sedan/2021/Overview/bmw-m5-cs-onepager-mc-m5-core-highlights-hero-teaser-desktop.jpg/jcr:content/renditions/cq5dam.resized.img.1680.large.time1627456764859.jpg",
  },
  // {
  //   brand: "",
  //   model: "",
  //   year: 2020,
  //   fuel_type: "",
  //   horse_power: 1,
  //   gearbox: "",
  //   combustion: 1,
  //   price_category: "Basic",
  //   available: true,
  // },
];
